// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AddressTreeviewController from "./address_treeview_controller"
application.register("address-treeview", AddressTreeviewController)

import RemoveNestedFormController from "./remove_nested_form_controller"
application.register("remove-nested-form", RemoveNestedFormController)
