// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import BeneficiaryAddressesFilterFieldController from "./beneficiary_addresses_filter_field_controller"
application.register("beneficiary-addresses-filter-field", BeneficiaryAddressesFilterFieldController)

import FilterFieldController from "./filter_field_controller"
application.register("filter-field", FilterFieldController)

import NotificationsStatsChartController from "./notifications_stats_chart_controller"
application.register("notifications-stats-chart", NotificationsStatsChartController)

import RemoveNestedFormController from "./remove_nested_form_controller"
application.register("remove-nested-form", RemoveNestedFormController)

import TreeviewController from "./treeview_controller"
application.register("treeview", TreeviewController)
