delay: 15
concurrency: 25
polling_strategy: StrictPriority
queues:
  - [<%= ENV.fetch("AWS_SQS_HIGH_PRIORITY_QUEUE_NAME", "high-priority") %>]
  - [<%= ENV.fetch("AWS_SQS_DEFAULT_QUEUE_NAME", "default-priority") %>]
  - [<%= ENV.fetch("AWS_SQS_LOW_PRIORITY_QUEUE_NAME", "low-priority") %>]

groups:
  scheduler:
    concurrency: 3
    delay: 30
    queues:
      - <%= ENV.fetch("AWS_SQS_SCHEDULER_QUEUE_NAME", "scheduler") %>
